---
- name: ReportServer
  hosts: reportserver
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'



- name: ReportServer
  hosts: reportserver
  become: yes
  become_method: sudo
  remote_user: '{{admin_username}}'
  
  roles:
  - { role: common , tags: "common"} 
  - { role: mysql , tags: "mysql"}
  - { role: reportserver  , tags: "reportserver"} 
  - { role: nginx , tags: "nginx"}
  - { role: end , tags: "end"}

    