---
- name: ReportServer
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
  - { role: common , tags: "common"} 
  - { role: mysql , tags: "mysql"}
  - { role: reportserver  , tags: "reportserver"} 
  - { role: nginx , tags: "nginx"}

    